spring:
  application:
    name: gateway-service
  config:
    import: "optional:configserver:http://localhost:8091"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: product-composite
          uri: lb://PRODUCT-COMPOSITE
          predicates:
            - Path=/api/composite/**
          filters:
            - RewritePath=/api/composite/(?<segment>.*), /composites/$\{segment}
            - name: AuthorizationFilter  # ‚Üê AJOUTER LE FILTRE ICI

server:
  port: 8765

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    com.example.gateway.config: TRACE
    org.springframework.cloud.gateway: TRACE
    org.springframework.web.server: TRACE